### ISSUE TITLE
Jupyter notebook plot_scalable_poly_kernels dies when run on binder

### ISSUE THREAD

**Issue by asm582** [project-codeflare/codeflare#11]
**Describe the bug**
Jupyter notebook kernel dies

**To Reproduce**
1. Go to Binder
2. Click on plot_scalable_poly_kernels 
3. Run the notebook

**Expected behavior**
The jupyter notebook should run without error

**Comment by yuanchi2807** [comment]
Notebook error came from data loading at this step. Binder instance ran out of memory. Local notebook runs fine though. 

`X, y = fetch_covtype(return_X_y=True)`

**Comment by raghukiran1224** [comment]
closing as this is a binder related issue -- maybe we make a comment that some of the notebooks are constrained as binder does not work for larger datasets?
