### ISSUE TITLE
Replace SimlpleQueue

### ISSUE THREAD

**Issue by raghukiran1224** [project-codeflare/codeflare#15]
## Overview
Currently, lineage uses `SimpleQueue` to realize pipelines. But this is available only in `Python >=3.8`. This reduces adoption, moving to `Queue` will give us broader Python version coverage.

### Acceptance Criteria
- [x] Replace `SimpleQueue` with `Queue`
- [x] Ensure tests pass

### Questions
- What are the drawbacks of using `Queue` vs `SimpleQueue`?

### Reference
- https://towardsdatascience.com/dive-into-queue-module-in-python-its-more-than-fifo-ce86c40944ef

**Comment by aviolante** [comment]
@raghukiran1224 is this just a matter of `from queue import Queue` in the `Runtime.py` file and then changing lines 377 and 414 from `xyref_queue = SimpleQueue()` to `xyref_queue = Queue()`

**Comment by raghukiran1224** [comment]
@aviolante Perfect, thanks for the pointer :) Do you want to create a PR and be our first outside contributor? :)

**Comment by raghukiran1224** [comment]
@aviolante lol.. I just noticed you already did!

**Comment by aviolante** [comment]
@raghukiran1224 haha

**Comment by raghukiran1224** [comment]
validated on WS Python notebook and example works in a vanilla environment after `pip3 install --upgrade pip` and `pip3 install codeflare==0.1.2`, which is also the default now.
