### ISSUE TITLE
Predicted output is not properly assigned to get_yref(), instead is assigned to get_Xref()

### ISSUE THREAD

**Issue by raghukiran1224** [project-codeflare/codeflare#22]
**Describe the bug**
After running a `PREDICT`, the `y_pred `cannot be obtained via `get_yref()`, instead can be obtained via the `get_Xref() `.  Semantically, this seems weird.

**To Reproduce**
1. Go to https://github.ibm.com/codeflare/ray-pipeline/blob/complex-example-1/notebooks/plot_feature_selection_pipeline.ipynb
2. Scroll down to `y_pred = ray.get(predict_clf_output[0].get_yref())
3. If you change that statement to `y_pred = ray.get(predict_clf_output[0].get_Xref())` the output would match the original sklearn pipeline on the top.

**Expected behavior**
The predicted output should be obtained from calling `get_yref().`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raghukiran1224** [comment]
Created by @klwuibm

**Comment by klwuibm** [comment]
closing this issue.
