### ISSUE TITLE
Grid search jupyter notebook on binder missing graphviz library

### ISSUE THREAD

**Issue by asm582** [project-codeflare/codeflare#9]
Graph viz missing from binder service

**To Reproduce**
1. Go to binder service
2.Run Grid search notebook

**Additional context**

Below error caused by execution of cell:
```
non_param_graph = cf_utils.pipeline_to_graph(pipeline)
non_param_graph
```
ExecutableNotFound: failed to execute ['dot', '-Kdot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

**Comment by raghukiran1224** [comment]
@asm582 Graphviz needs a local installation of graphviz, we cannot visualize otherwise. Perhaps, we should not visualize this in the notebook?

**Comment by raghukiran1224** [comment]
wont fix as binder env is too small and we cannot have graphviz installed there
